version: "3"

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"

  wordpress:
    image: wordpress:latest
    ports:
      - "60000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "skim"
      WORDPRESS_DB_PASSWORD: "skim"
      WORDPRESS_DB_NAME: "wordpress"

volumes:
  db_data:
