version: '3'

volumes:
  wp_data: {}
  db_data: {}
services:
  mariadb:
    build : ./requirements/mariadb/
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
    env_file: .env
    tty: true

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    env_file: .env
    tty: true

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    hostname: skim.42.fr
    volumes:
      - wp_data:/var/www/html
    networks:
      - intra
    tty: true
networks:
  intra:
    driver: bridge
