version: '3'

volumes:
  wp_data: {}
  db_data: {}
services:
  mariadb:
    build : ./mariaDB/
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
    tty: true
  wordpress:
    build: ./wordpress/
    restart: always
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    tty: true
  nginx:
    depends_on:
      - wordpress
    build: ./nginx/
    environment:
      VIRTUAL_HOST: skim.42.fr
    restart: always
    ports:
      - "443:443"
    hostname: skim.42.fr
    volumes:
      - wp_data:/var/www/html
    networks:
      - intra
    tty: true
networks:
  intra:
    driver: bridge
